name: ono-tf2
channels:
  - rdkit
dependencies:
  - python=3.7.9
  - pip
  - rdkit=2020.03.3.0
  - pip:
    - tensorflow==2.2
    - joblib==0.17.0
    - wget==3.2
    - tensorflow_federated=0.16.1
    - mendeleev==0.6.0
    - oddt==0.1.9
    - pandas==1.1.3
    - click
